"""
generate_demand.py
------------------
Generates routes.rou.xml for the Michigan Ave & Livernois simulation
from raw demand parameters.

Demand is based on MDOT AADT estimates:
    Michigan Ave: ~20,000 vpd  (AADT)
    Livernois:    ~10,000 vpd  (AADT)

Peak hour volumes derived using K-factor = 0.09 (standard urban arterial).

Edit the DEMAND dict below to update volumes, then run:
    python simulation/demand/generate_demand.py

Output is written to simulation/routes.rou.xml.

Sources:
    MDOT Traffic Volumes Open Data Portal:
        https://gis-michigan.opendata.arcgis.com/datasets/mdot::2022-traffic-volumes
    SEMCOG Regional Traffic Counts Database:
        https://data.semcog.org/traffic-counts
    Detroit Open Data Portal:
        https://data.detroitmi.gov/maps/049ffe8e321b4a70a2b09dd66b9e0255
"""

import os

# ---------------------------------------------------------------------------
# Raw demand parameters — edit these to update the simulation
# ---------------------------------------------------------------------------

# Annual Average Daily Traffic (AADT) estimates from MDOT/SEMCOG
AADT = {
    "michigan_ave": 20_000,  # vehicles per day
    "livernois": 10_000,  # vehicles per day
}

# K-factor: fraction of AADT occurring in the peak hour (standard urban = 0.09)
K_FACTOR = 0.09

# Directional splits per period (fraction going each direction)
# Michigan Ave: westbound heavier in AM, eastbound heavier in PM
# Livernois: roughly balanced both directions
SPLITS = {
    "am": {
        "michigan_wb": 0.55,
        "michigan_eb": 0.45,
        "livernois_nb": 0.50,
        "livernois_sb": 0.50,
    },
    "pm": {
        "michigan_wb": 0.45,
        "michigan_eb": 0.55,
        "livernois_nb": 0.50,
        "livernois_sb": 0.50,
    },
    "offpeak": {
        "michigan_wb": 0.50,
        "michigan_eb": 0.50,
        "livernois_nb": 0.50,
        "livernois_sb": 0.50,
    },
}

# Off-peak volume as a fraction of peak hour volume
OFFPEAK_FACTOR = 0.44  # ~800 veh/hr on Michigan Ave vs 1800 peak

# Simulation time periods (in seconds)
# The simulation runs for MAX_STEPS = 3600 (1 hour).
# These periods are relative to simulation start.
# For a 1-hour sim, only one period applies — we model AM peak by default.
# To model a full day, increase MAX_STEPS in traffic_env.py to 86400.
PERIODS = {
    "am": {"begin": 0, "end": 7200},
    "offpeak": {"begin": 7200, "end": 57600},
    "pm": {"begin": 57600, "end": 64800},
}

# Edge IDs in the SUMO network (must match intersection.net.xml)
EDGES = {
    "michigan_wb": ("A1A0", "A0B0"),
    "michigan_eb": ("B0A0", "A0A1"),
    "livernois_nb": ("B1B0", "B0A0"),
    "livernois_sb": ("A0A1", "A1B1"),
}

# Output path — relative to this script's location
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "routes.rou.xml")


# ---------------------------------------------------------------------------
# Derived volumes
# ---------------------------------------------------------------------------


def compute_volumes():
    """Compute per-direction, per-period vehicle flow rates (veh/hr)."""
    peak_michigan = AADT["michigan_ave"] * K_FACTOR  # ~1800 veh/hr
    peak_livernois = AADT["livernois"] * K_FACTOR  # ~900 veh/hr
    offpeak_michigan = peak_michigan * OFFPEAK_FACTOR  # ~800 veh/hr
    offpeak_livernois = peak_livernois * OFFPEAK_FACTOR  # ~400 veh/hr

    volumes = {}
    for period in ["am", "pm", "offpeak"]:
        mich_total = offpeak_michigan if period == "offpeak" else peak_michigan
        liv_total = offpeak_livernois if period == "offpeak" else peak_livernois

        volumes[period] = {
            "michigan_wb": round(mich_total * SPLITS[period]["michigan_wb"]),
            "michigan_eb": round(mich_total * SPLITS[period]["michigan_eb"]),
            "livernois_nb": round(liv_total * SPLITS[period]["livernois_nb"]),
            "livernois_sb": round(liv_total * SPLITS[period]["livernois_sb"]),
        }
    return volumes


# ---------------------------------------------------------------------------
# XML generation
# ---------------------------------------------------------------------------


def generate_routes_xml(volumes):
    """Build the routes.rou.xml content as a string."""
    lines = []
    lines.append("<!-- routes.rou.xml — generated by generate_demand.py -->")
    lines.append("<!-- Michigan Ave & Livernois, Detroit                 -->")
    lines.append("")
    lines.append("<routes>")
    lines.append("")
    lines.append('    <vType id="car" accel="2.6" decel="4.5" sigma="0.5"')
    lines.append('           length="5" maxSpeed="13.89" color="0.7,0.7,0.7"/>')
    lines.append("")

    # Route definitions
    route_defs = {
        "michigan_wb": "mich_wb",
        "michigan_eb": "mich_eb",
        "livernois_nb": "liv_nb",
        "livernois_sb": "liv_sb",
    }
    for key, route_id in route_defs.items():
        edges = " ".join(EDGES[key])
        lines.append(f'    <route id="{route_id}" edges="{edges}"/>')
    lines.append("")

    # Flow definitions per period
    period_labels = {
        "am": "AM PEAK (7-9 AM)",
        "offpeak": "OFF-PEAK (9AM-4PM)",
        "pm": "PM PEAK (4-6PM)",
    }
    for period, label in period_labels.items():
        begin = PERIODS[period]["begin"]
        end = PERIODS[period]["end"]
        lines.append(f"    <!-- {label} -->")
        for key, route_id in route_defs.items():
            vph = volumes[period][key]
            flow_id = f"{period}_{route_id}"
            lines.append(f'    <flow id="{flow_id}" type="car" route="{route_id}"')
            lines.append(f'          begin="{begin}" end="{end}" vehsPerHour="{vph}"/>')
        lines.append("")

    lines.append("</routes>")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    volumes = compute_volumes()

    print("=== Demand Summary: Michigan Ave & Livernois ===\n")
    print(f"  AADT Michigan Ave : {AADT['michigan_ave']:,} vpd")
    print(f"  AADT Livernois    : {AADT['livernois']:,} vpd")
    print(f"  K-factor          : {K_FACTOR}\n")

    for period, vols in volumes.items():
        print(f"  {period.upper()}:")
        for direction, vph in vols.items():
            print(f"    {direction:<15}: {vph} veh/hr")
        print()

    xml = generate_routes_xml(volumes)

    with open(OUTPUT_PATH, "w") as f:
        f.write(xml)

    print(f"Written to: {os.path.abspath(OUTPUT_PATH)}")


if __name__ == "__main__":
    main()
